Repository rafaelbaptista13/projeto_ies, pull requests merged in 2020-12, with the labels that each got.

#15 Creation of controllers and exception
  Covinfo19/src/main/java/ua/ies/g23/Covinfo19/controller/HospitalController.java
  Covinfo19/src/main/java/ua/ies/g23/Covinfo19/controller/MedicoController.java
  Covinfo19/src/main/java/ua/ies/g23/Covinfo19/controller/PacienteController.java
  Covinfo19/src/main/java/ua/ies/g23/Covinfo19/controller/Relatorio_PacienteController.java
  Covinfo19/src/main/java/ua/ies/g23/Covinfo19/exception/ErrorDetails.java
  Covinfo19/src/main/java/ua/ies/g23/Covinfo19/exception/GlobalExceptionHandler.java
  Covinfo19/src/main/java/ua/ies/g23/Covinfo19/exception/ResourceNotFoundException.java
Labels: enhancement

#16 New/container mysql
  Covinfo19/src/main/java/ua/ies/g23/Covinfo19/model/Hospital.java
  Covinfo19/src/main/java/ua/ies/g23/Covinfo19/model/Medico.java
  Covinfo19/src/main/java/ua/ies/g23/Covinfo19/model/Paciente.java
  Covinfo19/src/main/java/ua/ies/g23/Covinfo19/model/Relatorio_Paciente.java
  Covinfo19/src/main/java/ua/ies/g23/Covinfo19/repository/HospitalRepository.java
  Covinfo19/src/main/java/ua/ies/g23/Covinfo19/repository/MedicoRepository.java
  Covinfo19/src/main/java/ua/ies/g23/Covinfo19/repository/PacienteRepository.java
  Covinfo19/src/main/java/ua/ies/g23/Covinfo19/repository/Relatorio_PacienteRepository.java
  Covinfo19/src/main/resources/application.properties
Labels: enhancement

#20 Insertion of data from script into DB
  Covinfo19/src/main/java/ua/ies/g23/Covinfo19/Covinfo19Application.java
  Covinfo19/src/main/java/ua/ies/g23/Covinfo19/Receiver.java
  Covinfo19/src/main/java/ua/ies/g23/Covinfo19/controller/PacienteController.java
  Covinfo19/src/main/java/ua/ies/g23/Covinfo19/model/Hospital.java
  Covinfo19/src/main/java/ua/ies/g23/Covinfo19/model/Paciente.java
Labels: enhancement

#21 Imp/report improvement
  report/projectSpecificationReport/IES-Project-Specification-Report.odt
  report/projectSpecificationReport/arquitetura.drawio
  report/projectSpecificationReport/arquitetura.png
  report/projectSpecificationReport/class diagram.png
  report/projectSpecificationReport/diagrama casos de uso.drawio
  report/projectSpecificationReport/diagrama casos de uso.png
  report/projectSpecificationReport/fontedados-servidor.drawio
  report/projectSpecificationReport/fontedados-servidor.png
Labels: documentation

#24 DB update with anonymization
  report/analiseRequisitosBD/AnaliseRequesitos.docx
  report/analiseRequisitosBD/AnaliseRequisitos.odt
  report/analiseRequisitosBD/DER.png
  report/analiseRequisitosBD/DER_IES.drawio
  report/analiseRequisitosBD/DER_IES.png
  report/analiseRequisitosBD/DER_anonymous_IES.drawio
  report/analiseRequisitosBD/DER_anonymous_IES.png
Labels: documentation

#25 Imp/report db update
  report/projectSpecificationReport/IES-Project-Specification-Report.odt
Labels: documentation

#26 Imp/connection dbs springboot
  Covinfo19/pom.xml
  Covinfo19/src/main/java/ua/ies/g23/Covinfo19/Covinfo19Application.java
  Covinfo19/src/main/java/ua/ies/g23/Covinfo19/Receiver.java
  Covinfo19/src/main/java/ua/ies/g23/Covinfo19/ReceiverUpdateData.java
  Covinfo19/src/main/java/ua/ies/g23/Covinfo19/Runner.java
  Covinfo19/src/main/java/ua/ies/g23/Covinfo19/pacientes_med_hosp/config/Pacientes_Med_HospConfig.java
  Covinfo19/src/main/java/ua/ies/g23/Covinfo19/pacientes_med_hosp/controller/HospitalController.java
  Covinfo19/src/main/java/ua/ies/g23/Covinfo19/pacientes_med_hosp/controller/MedicoController.java
  Covinfo19/src/main/java/ua/ies/g23/Covinfo19/pacientes_med_hosp/controller/PacienteController.java
  Covinfo19/src/main/java/ua/ies/g23/Covinfo19/pacientes_med_hosp/model/Hospital.java
  Covinfo19/src/main/java/ua/ies/g23/Covinfo19/pacientes_med_hosp/model/Medico.java
  Covinfo19/src/main/java/ua/ies/g23/Covinfo19/pacientes_med_hosp/model/Paciente.java
  Covinfo19/src/main/java/ua/ies/g23/Covinfo19/pacientes_med_hosp/repository/HospitalRepository.java
  Covinfo19/src/main/java/ua/ies/g23/Covinfo19/pacientes_med_hosp/repository/MedicoRepository.java
  Covinfo19/src/main/java/ua/ies/g23/Covinfo19/pacientes_med_hosp/repository/PacienteRepository.java
  Covinfo19/src/main/java/ua/ies/g23/Covinfo19/relatorios/config/RelatoriosConfig.java
  Covinfo19/src/main/java/ua/ies/g23/Covinfo19/relatorios/controller/CasoController.java
  Covinfo19/src/main/java/ua/ies/g23/Covinfo19/relatorios/controller/Relatorio_PacienteController.java
  Covinfo19/src/main/java/ua/ies/g23/Covinfo19/relatorios/model/Caso.java
  Covinfo19/src/main/java/ua/ies/g23/Covinfo19/relatorios/model/Relatorio_Paciente.java
  Covinfo19/src/main/java/ua/ies/g23/Covinfo19/relatorios/repository/CasoRepository.java
  Covinfo19/src/main/java/ua/ies/g23/Covinfo19/relatorios/repository/Relatorio_PacienteRepository.java
  Covinfo19/src/main/resources/application.properties
  Site/package-lock.json
Labels: improvement

#27 Number of cases by current state controllers
  Covinfo19/src/main/java/ua/ies/g23/Covinfo19/relatorios/controller/CasoController.java
  Covinfo19/src/main/java/ua/ies/g23/Covinfo19/relatorios/repository/CasoRepository.java
Labels: enhancement

#28 New/script update dados
  Covinfo19/src/main/java/ua/ies/g23/Covinfo19/Covinfo19Application.java
  Covinfo19/src/main/java/ua/ies/g23/Covinfo19/Receiver.java
  Covinfo19/src/main/java/ua/ies/g23/Covinfo19/ReceiverMedicosPacientes.java
  Covinfo19/src/main/java/ua/ies/g23/Covinfo19/ReceiverUpdateData.java
  Covinfo19/src/main/java/ua/ies/g23/Covinfo19/pacientes_med_hosp/model/Paciente.java
  Covinfo19/src/main/java/ua/ies/g23/Covinfo19/relatorios/controller/CasoController.java
  Covinfo19/src/main/java/ua/ies/g23/Covinfo19/relatorios/repository/CasoRepository.java
  Covinfo19/src/main/resources/application.properties
  README.md
  scriptDados/DataGeneration/src/main/java/ua/ies/g23/DataGeneration/DataGenerationApplication.java
  scriptDados/DataGeneration/src/main/java/ua/ies/g23/DataGeneration/Receiver.java
  scriptDados/DataGeneration/src/main/java/ua/ies/g23/DataGeneration/Runner.java
  scriptDados/readme.txt
  scriptDadosPrincipal/DataUpdate/src/main/java/ua/ies/g23/DataUpdate/DataUpdateApplication.java
  scriptDadosPrincipal/DataUpdate/src/main/java/ua/ies/g23/DataUpdate/Runner.java
Labels: enhancement

#29 Small update on database model
  report/analiseRequisitosBD/AnaliseRequisitos.odt
  report/analiseRequisitosBD/DER_IES.drawio
  report/analiseRequisitosBD/DER_IES.png
  report/projectSpecificationReport/IES-Project-Specification-Report.odt
Labels: documentation

#30 Hospital/Medico Script Creation
  Covinfo19/src/main/java/ua/ies/g23/Covinfo19/ReceiverMedicosPacientes.java
  Covinfo19/src/main/java/ua/ies/g23/Covinfo19/pacientes_med_hosp/controller/HospitalController.java
  Covinfo19/src/main/java/ua/ies/g23/Covinfo19/pacientes_med_hosp/controller/MedicoController.java
  Covinfo19/src/main/java/ua/ies/g23/Covinfo19/pacientes_med_hosp/model/Hospital.java
  Covinfo19/src/main/java/ua/ies/g23/Covinfo19/pacientes_med_hosp/model/Medico.java
  scriptHospitalMedicos/DataHospitalDoctors/.gitignore
  scriptHospitalMedicos/DataHospitalDoctors/.mvn/wrapper/MavenWrapperDownloader.java
  scriptHospitalMedicos/DataHospitalDoctors/.mvn/wrapper/maven-wrapper.jar
  scriptHospitalMedicos/DataHospitalDoctors/.mvn/wrapper/maven-wrapper.properties
  scriptHospitalMedicos/DataHospitalDoctors/mvnw
  scriptHospitalMedicos/DataHospitalDoctors/mvnw.cmd
  scriptHospitalMedicos/DataHospitalDoctors/pom.xml
  scriptHospitalMedicos/DataHospitalDoctors/src/main/java/ua/ies/g23/DataHospitalDoctors/DataHospitalDoctorsApplication.java
  scriptHospitalMedicos/DataHospitalDoctors/src/main/java/ua/ies/g23/DataHospitalDoctors/Runner.java
  scriptHospitalMedicos/DataHospitalDoctors/src/main/resources/application.properties
  scriptHospitalMedicos/DataHospitalDoctors/src/test/java/ua/ies/g23/DataHospitalDoctors/DataHospitalDoctorsApplicationTests.java
Labels: enhancement

#31 Imp/casos controller services
  Covinfo19/src/main/java/ua/ies/g23/Covinfo19/ReceiverMedicosPacientes.java
  Covinfo19/src/main/java/ua/ies/g23/Covinfo19/pacientes_med_hosp/repository/PacienteRepository.java
  Covinfo19/src/main/java/ua/ies/g23/Covinfo19/relatorios/controller/CasoController.java
  Covinfo19/src/main/java/ua/ies/g23/Covinfo19/relatorios/repository/CasoRepository.java
  scriptDadosPrincipal/DataUpdate/src/main/java/ua/ies/g23/DataUpdate/Runner.java
Labels: improvement

#32 connection between api and daily statistics webpage
  Covinfo19/src/main/java/ua/ies/g23/Covinfo19/relatorios/controller/CasoController.java
  Site/package-lock.json
  Site/src/app/app.module.ts
  Site/src/app/caso.ts
  Site/src/app/casos.service.spec.ts
  Site/src/app/casos.service.ts
  Site/src/app/paciente.ts
  Site/src/app/pacientes.service.spec.ts
  Site/src/app/pacientes.service.ts
  Site/src/app/statistics/statistics.component.html
  Site/src/app/statistics/statistics.component.ts
  Site/src/index.html
Labels: enhancement

#35 Api services with filters for Hospitais, Pacientes and Caso
  Covinfo19/src/main/java/ua/ies/g23/Covinfo19/pacientes_med_hosp/controller/HospitalController.java
  Covinfo19/src/main/java/ua/ies/g23/Covinfo19/pacientes_med_hosp/controller/PacienteController.java
  Covinfo19/src/main/java/ua/ies/g23/Covinfo19/pacientes_med_hosp/repository/HospitalRepository.java
  Covinfo19/src/main/java/ua/ies/g23/Covinfo19/pacientes_med_hosp/repository/PacienteRepository.java
  Covinfo19/src/main/java/ua/ies/g23/Covinfo19/relatorios/controller/CasoController.java
  Covinfo19/src/main/java/ua/ies/g23/Covinfo19/relatorios/repository/CasoRepository.java
Labels: enhancement

#36 Addition of search filters and two new charts, prototype version
  Site/src/app/home/home.component.html
  Site/src/app/login/login.component.html
  Site/src/app/statistics/statistics.component.css
  Site/src/app/statistics/statistics.component.html
  Site/src/app/statistics/statistics.component.ts
Labels: improvement

#38 Update attr numero_camas_ocupadas dynamically
  Covinfo19/src/main/java/ua/ies/g23/Covinfo19/Receiver.java
  Covinfo19/src/main/java/ua/ies/g23/Covinfo19/ReceiverUpdateData.java
  Covinfo19/src/main/java/ua/ies/g23/Covinfo19/pacientes_med_hosp/controller/MedicoController.java
  Covinfo19/src/main/java/ua/ies/g23/Covinfo19/pacientes_med_hosp/model/Paciente.java
  Covinfo19/src/main/java/ua/ies/g23/Covinfo19/pacientes_med_hosp/repository/MedicoRepository.java
  scriptDadosPrincipal/DataUpdate/src/main/java/ua/ies/g23/DataUpdate/Runner.java
Labels: improvement

#39 Allow count casos with filters
  Covinfo19/src/main/java/ua/ies/g23/Covinfo19/relatorios/controller/CasoController.java
Labels: improvement

#40 Implementation of filters on the main statistics
  Site/src/app/app.module.ts
  Site/src/app/casos.service.ts
  Site/src/app/statistics/statistics.component.html
  Site/src/app/statistics/statistics.component.ts
  scriptDados/DataGeneration/src/main/java/ua/ies/g23/DataGeneration/Runner.java
Labels: enhancement

#41 Documentation and refactoring of project
  Covinfo19/src/main/java/ua/ies/g23/Covinfo19/Covinfo19Application.java
  Covinfo19/src/main/java/ua/ies/g23/Covinfo19/ReceiverGeracaoDados.java
  Covinfo19/src/main/java/ua/ies/g23/Covinfo19/ReceiverMedicosPacientes.java
  Covinfo19/src/main/java/ua/ies/g23/Covinfo19/ReceiverUpdateData.java
  Covinfo19/src/main/java/ua/ies/g23/Covinfo19/pacientes_med_hosp/config/Pacientes_Med_HospConfig.java
  Covinfo19/src/main/java/ua/ies/g23/Covinfo19/pacientes_med_hosp/repository/HospitalRepository.java
  Covinfo19/src/main/java/ua/ies/g23/Covinfo19/pacientes_med_hosp/repository/MedicoRepository.java
  Covinfo19/src/main/java/ua/ies/g23/Covinfo19/pacientes_med_hosp/repository/PacienteRepository.java
  Covinfo19/src/main/java/ua/ies/g23/Covinfo19/relatorios/config/RelatoriosConfig.java
  Covinfo19/src/main/java/ua/ies/g23/Covinfo19/relatorios/controller/CasoController.java
  Covinfo19/src/main/java/ua/ies/g23/Covinfo19/relatorios/repository/CasoRepository.java
  Site/src/app/app-routing.module.ts
  Site/src/app/caso.ts
  Site/src/app/casos.service.ts
  Site/src/app/login/login.component.ts
  Site/src/app/statistics/statistics.component.ts
  scriptDados/DataGeneration/src/main/java/ua/ies/g23/DataGeneration/DataGenerationApplication.java
  scriptDados/DataGeneration/src/main/java/ua/ies/g23/DataGeneration/Runner.java
  scriptDadosPrincipal/DataUpdate/src/main/java/ua/ies/g23/DataUpdate/DataUpdateApplication.java
  scriptDadosPrincipal/DataUpdate/src/main/java/ua/ies/g23/DataUpdate/Receiver.java
  scriptDadosPrincipal/DataUpdate/src/main/java/ua/ies/g23/DataUpdate/Runner.java
  scriptHospitalMedicos/DataHospitalDoctors/src/main/java/ua/ies/g23/DataHospitalDoctors/DataHospitalDoctorsApplication.java
  scriptHospitalMedicos/DataHospitalDoctors/src/main/java/ua/ies/g23/DataHospitalDoctors/Receiver.java
  scriptHospitalMedicos/DataHospitalDoctors/src/main/java/ua/ies/g23/DataHospitalDoctors/Runner.java
Labels: documentation

#43 Graphs for statistics web page
  Covinfo19/src/main/java/ua/ies/g23/Covinfo19/Runner.java
  Covinfo19/src/main/java/ua/ies/g23/Covinfo19/relatorios/controller/CasoController.java
  Covinfo19/src/main/java/ua/ies/g23/Covinfo19/relatorios/repository/Relatorio_PacienteRepository.java
  Site/src/app/casos.service.ts
  Site/src/app/statistics/statistics.component.ts
  scriptHospitalMedicos/DataHospitalDoctors/src/main/java/ua/ies/g23/DataHospitalDoctors/Runner.java
Labels: enhancement
