Repository rafaelbaptista13/projeto_ies, pull requests merged in 2021-01, with the labels that each got.

#44 Report Update
  report/projectSpecificationReport/IES-Project-Specification-Report.odt
  report/projectSpecificationReport/arquitetura.drawio
  report/projectSpecificationReport/arquitetura.png
  report/projectSpecificationReport/backend-database.drawio
  report/projectSpecificationReport/backend-database.png
  report/projectSpecificationReport/class diagram.png
  report/projectSpecificationReport/cliente-backend.drawio
  report/projectSpecificationReport/cliente-backend.png
  report/projectSpecificationReport/cliente-servidor.drawio
  report/projectSpecificationReport/cliente-servidor.png
  report/projectSpecificationReport/database.drawio
  report/projectSpecificationReport/database.png
  report/projectSpecificationReport/diagrama classes.png
  report/projectSpecificationReport/fontedados-backend.drawio
  report/projectSpecificationReport/fontedados-backend.png
  report/projectSpecificationReport/fontedados-servidor.png
Labels: documentation

#45 Creation of Hospitals statistics table
  Covinfo19/src/main/java/ua/ies/g23/Covinfo19/pacientes_med_hosp/controller/HospitalController.java
  Covinfo19/src/main/java/ua/ies/g23/Covinfo19/pacientes_med_hosp/repository/PacienteRepository.java
  Covinfo19/src/main/java/ua/ies/g23/Covinfo19/relatorios/controller/CasoController.java
  Site/src/app/casos.service.ts
  Site/src/app/hospital.service.spec.ts
  Site/src/app/hospital.service.ts
  Site/src/app/hospital/hospital.component.html
  Site/src/app/hospital/hospital.component.ts
  Site/src/app/statistics/statistics.component.ts
Labels: enhancement

#46 Bugs fixed
  Site/src/app/hospital.service.ts
  Site/src/app/hospital/hospital.component.ts
Labels: bug

#47 Improvements on CSS
  Site/src/app/home/home.component.css
  Site/src/app/home/home.component.html
  Site/src/app/hospital/hospital.component.css
  Site/src/app/hospital/hospital.component.html
  Site/src/app/login/login.component.html
  Site/src/app/login/login.component.ts
  Site/src/app/statistics/statistics.component.css
  Site/src/app/statistics/statistics.component.html
Labels: bug

#48 Implementation of login with jwt
  Covinfo19/pom.xml
  Covinfo19/src/main/java/ua/ies/g23/Covinfo19/Covinfo19Application.java
  Covinfo19/src/main/java/ua/ies/g23/Covinfo19/JWTAuthenticationFilter.java
  Covinfo19/src/main/java/ua/ies/g23/Covinfo19/JWTAuthorizationFilter.java
  Covinfo19/src/main/java/ua/ies/g23/Covinfo19/ReceiverMedicosPacientes.java
  Covinfo19/src/main/java/ua/ies/g23/Covinfo19/SecurityConstants.java
  Covinfo19/src/main/java/ua/ies/g23/Covinfo19/UserDetailsServiceImpl.java
  Covinfo19/src/main/java/ua/ies/g23/Covinfo19/WebSecurity.java
  Covinfo19/src/main/java/ua/ies/g23/Covinfo19/pacientes_med_hosp/controller/HospitalController.java
  Covinfo19/src/main/java/ua/ies/g23/Covinfo19/pacientes_med_hosp/controller/MedicoController.java
  Covinfo19/src/main/java/ua/ies/g23/Covinfo19/pacientes_med_hosp/controller/PacienteController.java
  Covinfo19/src/main/java/ua/ies/g23/Covinfo19/pacientes_med_hosp/model/Medico.java
  Covinfo19/src/main/java/ua/ies/g23/Covinfo19/pacientes_med_hosp/repository/MedicoRepository.java
  Covinfo19/src/main/java/ua/ies/g23/Covinfo19/relatorios/controller/CasoController.java
  Covinfo19/src/main/java/ua/ies/g23/Covinfo19/relatorios/controller/Relatorio_PacienteController.java
  Site/package-lock.json
  Site/src/app/app-routing.module.ts
  Site/src/app/app.module.ts
  Site/src/app/casos.service.ts
  Site/src/app/hospital.service.ts
  Site/src/app/hospital/hospital.component.html
  Site/src/app/login.service.spec.ts
  Site/src/app/login.service.ts
  Site/src/app/login/login.component.css
  Site/src/app/login/login.component.html
  Site/src/app/login/login.component.spec.ts
  Site/src/app/login/login.component.ts
  Site/src/app/pacientes.service.spec.ts
  Site/src/app/pacientes.service.ts
  Site/src/app/statistics/statistics.component.html
  scriptHospitalMedicos/DataHospitalDoctors/src/main/java/ua/ies/g23/DataHospitalDoctors/Runner.java
Labels: enhancement

#51 Documentation Page Implemented
  Covinfo19/pom.xml
  Covinfo19/src/main/java/ua/ies/g23/Covinfo19/SwaggerConfig.java
  Covinfo19/src/main/java/ua/ies/g23/Covinfo19/WebSecurity.java
  scriptHospitalMedicos/DataHospitalDoctors/src/main/java/ua/ies/g23/DataHospitalDoctors/Runner.java
Labels: documentation

#52 Virtual Machine Configuration
  Covinfo19/src/main/resources/application.properties
  Dockerfile
  Site/Dockerfile
  Site/nginx.conf
  Site/src/app/casos.service.ts
  Site/src/app/hospital.service.ts
  Site/src/app/login.service.ts
  docker-compose.yml
  scriptDados/DataGeneration/src/main/java/ua/ies/g23/DataGeneration/Runner.java
Labels: enhancement

#53 Pagination Implementation
  Covinfo19/src/main/java/ua/ies/g23/Covinfo19/pacientes_med_hosp/controller/HospitalController.java
  Covinfo19/src/main/java/ua/ies/g23/Covinfo19/pacientes_med_hosp/controller/MedicoController.java
  Covinfo19/src/main/java/ua/ies/g23/Covinfo19/pacientes_med_hosp/controller/PacienteController.java
  Covinfo19/src/main/java/ua/ies/g23/Covinfo19/pacientes_med_hosp/repository/HospitalRepository.java
  Covinfo19/src/main/java/ua/ies/g23/Covinfo19/pacientes_med_hosp/repository/MedicoRepository.java
  Covinfo19/src/main/java/ua/ies/g23/Covinfo19/pacientes_med_hosp/repository/PacienteRepository.java
  Covinfo19/src/main/java/ua/ies/g23/Covinfo19/relatorios/controller/CasoController.java
  Covinfo19/src/main/java/ua/ies/g23/Covinfo19/relatorios/controller/Relatorio_PacienteController.java
  Covinfo19/src/main/java/ua/ies/g23/Covinfo19/relatorios/repository/CasoRepository.java
Labels: enhancement

#54 Add_Edit page continuation
  Covinfo19/src/main/java/ua/ies/g23/Covinfo19/pacientes_med_hosp/controller/MedicoController.java
  Covinfo19/src/main/java/ua/ies/g23/Covinfo19/pacientes_med_hosp/controller/PacienteController.java
  Covinfo19/src/main/java/ua/ies/g23/Covinfo19/pacientes_med_hosp/repository/PacienteRepository.java
  Site/src/app/home-medic/home-medic.component.ts
  Site/src/app/medic.service.ts
  Site/src/app/paciente/paciente.component.html
  Site/src/app/paciente/paciente.component.ts
Labels: enhancement

#56 Fixed navbar from homepage
  Site/src/app/home/home.component.css
  Site/src/app/home/home.component.html
Labels: improvement

#58 Controllers Fixed
  Covinfo19/src/main/java/ua/ies/g23/Covinfo19/pacientes_med_hosp/controller/PacienteController.java
  Covinfo19/src/main/java/ua/ies/g23/Covinfo19/relatorios/controller/CasoController.java
Labels: bug

#62 About us page
  Site/src/app/aboutus/aboutus.component.css
  Site/src/app/aboutus/aboutus.component.html
  Site/src/assets/Static/images/amaral.jpg
  Site/src/assets/Static/images/cruz.jpg
  Site/src/assets/Static/images/diogo.jpg
  Site/src/assets/Static/images/rafa.jpg
Labels: enhancement

#63 Events Implementation
  Covinfo19/src/main/java/ua/ies/g23/Covinfo19/ReceiverGeracaoDados.java
  Covinfo19/src/main/java/ua/ies/g23/Covinfo19/pacientes_med_hosp/controller/Event_CasoDiarioController.java
  Covinfo19/src/main/java/ua/ies/g23/Covinfo19/pacientes_med_hosp/controller/Event_HospitaisController.java
  Covinfo19/src/main/java/ua/ies/g23/Covinfo19/pacientes_med_hosp/controller/PacienteController.java
  Covinfo19/src/main/java/ua/ies/g23/Covinfo19/pacientes_med_hosp/model/Event_CasoDiario.java
  Covinfo19/src/main/java/ua/ies/g23/Covinfo19/pacientes_med_hosp/model/Event_Hospitais.java
  Covinfo19/src/main/java/ua/ies/g23/Covinfo19/pacientes_med_hosp/model/Paciente.java
  Covinfo19/src/main/java/ua/ies/g23/Covinfo19/pacientes_med_hosp/repository/Event_CasoDiarioRepository.java
  Covinfo19/src/main/java/ua/ies/g23/Covinfo19/pacientes_med_hosp/repository/Event_HospitaisRepository.java
  Covinfo19/src/main/java/ua/ies/g23/Covinfo19/relatorios/controller/CasoController.java
  Site/src/app/casos.service.ts
  Site/src/app/casosdiarios/casosdiarios.component.html
  Site/src/app/casosdiarios/casosdiarios.component.ts
  Site/src/app/hospital.service.ts
  Site/src/app/hospital/hospital.component.html
  Site/src/app/hospital/hospital.component.ts
  scriptDados/DataGeneration/src/main/java/ua/ies/g23/DataGeneration/Runner.java
Labels: enhancement

#64 Fixed missing paginators
  Covinfo19/src/main/java/ua/ies/g23/Covinfo19/pacientes_med_hosp/controller/Event_CasoDiarioController.java
  Covinfo19/src/main/java/ua/ies/g23/Covinfo19/pacientes_med_hosp/controller/Event_HospitaisController.java
  Covinfo19/src/main/java/ua/ies/g23/Covinfo19/pacientes_med_hosp/controller/PacienteController.java
  Covinfo19/src/main/java/ua/ies/g23/Covinfo19/pacientes_med_hosp/repository/PacienteRepository.java
  Covinfo19/src/main/java/ua/ies/g23/Covinfo19/relatorios/controller/Relatorio_PacienteController.java
  Covinfo19/src/main/java/ua/ies/g23/Covinfo19/relatorios/repository/Relatorio_PacienteRepository.java
  Covinfo19/src/main/resources/static/css/index.css
  Covinfo19/src/main/resources/static/css/login_style.css
  Covinfo19/src/main/resources/static/css/style.css
  Covinfo19/src/main/resources/static/images/background.png
  Covinfo19/src/main/resources/static/images/icons/account.png
  Covinfo19/src/main/resources/static/images/icons/logout.png
  Covinfo19/src/main/resources/static/js/homepage.js
  Covinfo19/src/main/resources/static/js/statistics.js
  Covinfo19/src/main/resources/templates/add_pacients.html
  Covinfo19/src/main/resources/templates/edit_pacients.html
  Covinfo19/src/main/resources/templates/index.html
  Covinfo19/src/main/resources/templates/index_logged.html
  Covinfo19/src/main/resources/templates/info.html
  Covinfo19/src/main/resources/templates/login.html
  Covinfo19/src/main/resources/templates/statistics.html
  Site/src/app/casosdiarios/casosdiarios.component.ts
  Site/src/app/statistics/statistics.component.ts
Labels: bug

#65 Fix VM Version
  Covinfo19/src/main/java/ua/ies/g23/Covinfo19/WebSecurity.java
  Covinfo19/src/main/java/ua/ies/g23/Covinfo19/pacientes_med_hosp/controller/Event_CasoDiarioController.java
  Covinfo19/src/main/java/ua/ies/g23/Covinfo19/pacientes_med_hosp/controller/Event_HospitaisController.java
  Covinfo19/src/main/java/ua/ies/g23/Covinfo19/pacientes_med_hosp/controller/HospitalController.java
  Covinfo19/src/main/java/ua/ies/g23/Covinfo19/pacientes_med_hosp/controller/PacienteController.java
  Covinfo19/src/main/java/ua/ies/g23/Covinfo19/relatorios/controller/CasoController.java
  Covinfo19/src/main/resources/application.properties
  Site/src/app/casos.service.ts
  Site/src/app/hospital.service.ts
  Site/src/app/login.service.ts
  Site/src/app/medic.service.ts
  Site/src/app/paciente.service.ts
  Site/src/app/paciente/paciente.component.ts
  Site/src/app/relatoriopaciente.service.ts
  docker-compose.yml
  run in background.txt
  scriptDados/DataGeneration/src/main/java/ua/ies/g23/DataGeneration/Runner.java
Labels: improvement
